# MongoDB
MONGO_URI=mongodb+srv://sulavspkt10_db_user:Admin1234@clustertest.mjsoisz.mongodb.net/weatherapp?retryWrites=true&w=majority&appName=ClusterTest

# Database name
DB_NAME=weatherapp

# OpenWeatherMap
WEATHER_API_KEY=2e6a6fee052c531746a388858442c31a

# Server
PORT=4567